default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("TATL_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("TATL_DB_PORT", 5432) %>
  username: <%= ENV.fetch("TATL_DB_USERNAME", "tatl") %>
  password: <%= ENV.fetch("TATL_DB_PASSWORD", "tatl_dev") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("TATL_DB_NAME", "tatl_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("TATL_TEST_DB_NAME", "tatl_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("TATL_DB_NAME", "tatl_production") %>
    username: <%= ENV.fetch("TATL_DB_USERNAME", "tatl") %>
    password: <%= ENV["TATL_DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("TATL_CACHE_DB_NAME", "tatl_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("TATL_QUEUE_DB_NAME", "tatl_production_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("TATL_CABLE_DB_NAME", "tatl_production_cable") %>
    migrations_paths: db/cable_migrate
