---
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/LineLength:
        Max: 250
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
exclude:
  - "vendor/**/*"
  - "node_modules/**/*"
